### ISSUE TITLE
Fatal crash when opening Oven GUI

### ISSUE THREAD

**Issue by Kryyss** [wyldmods/KitchenCraft#11]
Upon right clicking the oven to use it, the game instantly crashes back to the desktop with the following error:

-----
java.lang.NoClassDefFoundError: org/wyldmods/kitchencraft/machines/common/tile/TileOvenRF
	at org.wyldmods.kitchencraft.machines.common.container.ContainerOven.<init>(ContainerOven.java:77)
	at org.wyldmods.kitchencraft.machines.client.gui.GuiOven.<init>(GuiOven.java:27)
	at org.wyldmods.kitchencraft.machines.client.gui.GuiHandlerKC.getClientGuiElement(GuiHandlerKC.java:47)
	at cpw.mods.fml.common.network.NetworkRegistry.getLocalGuiContainer(NetworkRegistry.java:263)
	at cpw.mods.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:93)
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2209)
	at org.wyldmods.kitchencraft.machines.common.block.container.BlockOven.func_149727_a(BlockOven.java:127)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:326)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1435)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1941)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: org.wyldmods.kitchencraft.machines.common.tile.TileOvenRF
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 19 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at org.wyldmods.kitchencraft.machines.common.container.ContainerOven.<init>(ContainerOven.java:77)
	at org.wyldmods.kitchencraft.machines.client.gui.GuiOven.<init>(GuiOven.java:27)
	at org.wyldmods.kitchencraft.machines.client.gui.GuiHandlerKC.getClientGuiElement(GuiHandlerKC.java:47)
	at cpw.mods.fml.common.network.NetworkRegistry.getLocalGuiContainer(NetworkRegistry.java:263)
	at cpw.mods.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:93)
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2209)
	at org.wyldmods.kitchencraft.machines.common.block.container.BlockOven.func_149727_a(BlockOven.java:127)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:326)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1435)
-----

This is using the latest Force and 1.7.10.

**Comment by tterrag1098** [comment]
This crash should be fixed, what version are you using?

**Comment by Kryyss** [comment]
KitchenCraft-MC1.7.10-0.0.1-59-combo using AppleCore-mc1.7.10-1.1.0. Both of which are listed on Curse as being the latest builds.
