### ISSUE TITLE
Client shut down

### ISSUE THREAD

**Issue by FuYang001** [wyldmods/KitchenCraft#19]
[16:57:31] [NEI Item Loading/INFO] [STDOUT/]: [org.wyldmods.kitchencraft.machines.KitchenCraftMachines:loadRF:68]: Checking RF: true
[16:57:33] [NEI Item Loading/INFO] [STDOUT/]: [org.wyldmods.kitchencraft.machines.KitchenCraftMachines:loadRF:68]: Checking RF: true
[16:57:35] [Client thread/ERROR] [NotEnoughItems/]: Error loading recipe: 
java.lang.ArrayIndexOutOfBoundsException: 9
	at codechicken.nei.recipe.ShapelessRecipeHandler$CachedShapelessRecipe.setIngredients(ShapelessRecipeHandler.java:53) ~[ShapelessRecipeHandler$CachedShapelessRecipe.class:?]
	at codechicken.nei.recipe.ShapelessRecipeHandler$CachedShapelessRecipe.<init>(ShapelessRecipeHandler.java:47) ~[ShapelessRecipeHandler$CachedShapelessRecipe.class:?]
	at codechicken.nei.recipe.ShapelessRecipeHandler.forgeShapelessRecipe(ShapelessRecipeHandler.java:160) [ShapelessRecipeHandler.class:?]
	at codechicken.nei.recipe.ShapelessRecipeHandler.loadUsageRecipes(ShapelessRecipeHandler.java:129) [ShapelessRecipeHandler.class:?]
	at codechicken.nei.recipe.TemplateRecipeHandler.loadUsageRecipes(TemplateRecipeHandler.java:350) [TemplateRecipeHandler.class:?]
	at codechicken.nei.recipe.TemplateRecipeHandler.getUsageHandler(TemplateRecipeHandler.java:472) [TemplateRecipeHandler.class:?]
	at codechicken.nei.recipe.GuiUsageRecipe.openRecipeGui(GuiUsageRecipe.java:20) [GuiUsageRecipe.class:?]
	at codechicken.nei.recipe.RecipeItemInputHandler.lastKeyTyped(RecipeItemInputHandler.java:20) [RecipeItemInputHandler.class:?]
	at codechicken.nei.guihook.GuiContainerManager.lastKeyTyped(GuiContainerManager.java:307) [GuiContainerManager.class:?]
	at net.minecraft.client.gui.inventory.GuiContainer.func_73869_a(GuiContainer.java) [bex.class:?]
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73869_a(GuiContainerCreative.java:301) [bfl.class:?]
	at net.minecraft.client.gui.inventory.GuiContainer.public_func_73869_a(GuiContainer.java) [bex.class:?]
	at codechicken.nei.guihook.GuiContainerManager.callKeyTyped(GuiContainerManager.java) [GuiContainerManager.class:?]
	at codechicken.nei.guihook.GuiContainerManager.keyTyped(GuiContainerManager.java:475) [GuiContainerManager.class:?]
	at codechicken.nei.guihook.GuiContainerManager.handleKeyboardInput(GuiContainerManager.java:465) [GuiContainerManager.class:?]
	at net.minecraft.client.gui.inventory.GuiContainer.func_146282_l(GuiContainer.java) [bex.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:276) [bdw.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[16:57:35] [Client thread/DEBUG] [taam/]: Fetching ore dict recipes for machine 1: 1xtile.1hb@0->0 matches
[16:57:35] [Client thread/DEBUG] [taam/]: Fetching ore dict recipes for machine 0: 1xtile.1hb@0->0 matches
[16:57:36] [NEI Item Loading/INFO] [STDOUT/]: [org.wyldmods.kitchencraft.machines.KitchenCraftMachines:loadRF:68]: Checking RF: true
[16:57:36] [NEI Item Loading/INFO] [STDOUT/]: [org.wyldmods.kitchencraft.machines.KitchenCraftMachines:loadRF:68]: Checking RF: true
[16:58:08] [NEI Item Loading/INFO] [STDOUT/]: [org.wyldmods.kitchencraft.machines.KitchenCraftMachines:loadRF:68]: Checking RF: true

**Comment by tterrag1098** [comment]
This seems unrelated to the mod
